site_name: Phabfive
theme: readthedocs
repo_url: https://github.com/dynamist/phabfive

pages:
    - Introduction: 'index.md'
    - Development: 'development.md'

markdown_extensions:
    - admonition:
